<?php

namespace Database\Seeders;

//use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Katakana;

class KatakanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $characters = [
            ['character' => 'ア', 'sound' => 'a', 'lesson' => 1],
            ['character' => 'イ', 'sound' => 'i', 'lesson' => 1],
            ['character' => 'ウ', 'sound' => 'u', 'lesson' => 1],
            ['character' => 'エ', 'sound' => 'e', 'lesson' => 1],
            ['character' => 'オ', 'sound' => 'o', 'lesson' => 1],
            ['character' => 'カ', 'sound' => 'ka', 'lesson' => 1],
            ['character' => 'キ', 'sound' => 'ki', 'lesson' => 1],
            ['character' => 'ク', 'sound' => 'ku', 'lesson' => 1],
            ['character' => 'ケ', 'sound' => 'ke', 'lesson' => 1],
            ['character' => 'コ', 'sound' => 'ko', 'lesson' => 1],
            ['character' => 'サ', 'sound' => 'sa', 'lesson' => 2],
            ['character' => 'シ', 'sound' => 'shi', 'lesson' => 2],
            ['character' => 'ス', 'sound' => 'su', 'lesson' => 2],
            ['character' => 'セ', 'sound' => 'se', 'lesson' => 2],
            ['character' => 'ソ', 'sound' => 'so', 'lesson' => 2],
            ['character' => 'タ', 'sound' => 'ta', 'lesson' => 2],
            ['character' => 'チ', 'sound' => 'chi', 'lesson' => 2],
            ['character' => 'ツ', 'sound' => 'tsu', 'lesson' => 2],
            ['character' => 'テ', 'sound' => 'te', 'lesson' => 2],
            ['character' => 'ト', 'sound' => 'to', 'lesson' => 2],
            ['character' => 'ナ', 'sound' => 'na', 'lesson' => 3],
            ['character' => 'ニ', 'sound' => 'ni', 'lesson' => 3],
            ['character' => 'ヌ', 'sound' => 'nu', 'lesson' => 3],
            ['character' => 'ネ', 'sound' => 'ne', 'lesson' => 3],
            ['character' => 'ノ', 'sound' => 'no', 'lesson' => 3],
            ['character' => 'ン', 'sound' => 'n', 'lesson' => 3],
            ['character' => 'ハ', 'sound' => 'ha', 'lesson' => 3],
            ['character' => 'ヒ', 'sound' => 'hi', 'lesson' => 3],
            ['character' => 'フ', 'sound' => 'fu', 'lesson' => 3],
            ['character' => 'ヘ', 'sound' => 'he', 'lesson' => 3],
            ['character' => 'ホ', 'sound' => 'ho', 'lesson' => 3],
            ['character' => 'ヤ', 'sound' => 'ya', 'lesson' => 3],
            ['character' => 'ユ', 'sound' => 'yu', 'lesson' => 3],
            ['character' => 'ヨ', 'sound' => 'yo', 'lesson' => 3],
            ['character' => 'マ', 'sound' => 'ma', 'lesson' => 4],
            ['character' => 'ミ', 'sound' => 'mi', 'lesson' => 4],
            ['character' => 'ム', 'sound' => 'mu', 'lesson' => 4],
            ['character' => 'メ', 'sound' => 'me', 'lesson' => 4],
            ['character' => 'モ', 'sound' => 'mo', 'lesson' => 4],
            ['character' => 'ラ', 'sound' => 'ra', 'lesson' => 4],
            ['character' => 'リ', 'sound' => 'ri', 'lesson' => 4],
            ['character' => 'ル', 'sound' => 'ru', 'lesson' => 4],
            ['character' => 'レ', 'sound' => 're', 'lesson' => 4],
            ['character' => 'ロ', 'sound' => 'ro', 'lesson' => 4],
            ['character' => 'ワ', 'sound' => 'wa', 'lesson' => 4],
            ['character' => 'ヲ', 'sound' => 'wo', 'lesson' => 4],
            ['character' => 'ガ', 'sound' => 'ga', 'lesson' => 5],
            ['character' => 'ギ', 'sound' => 'gi', 'lesson' => 5],
            ['character' => 'グ', 'sound' => 'gu', 'lesson' => 5],
            ['character' => 'ゲ', 'sound' => 'ge', 'lesson' => 5],
            ['character' => 'ゴ', 'sound' => 'go', 'lesson' => 5],
            ['character' => 'ザ', 'sound' => 'za', 'lesson' => 5],
            ['character' => 'ジ', 'sound' => 'ji', 'lesson' => 5],
            ['character' => 'ズ', 'sound' => 'zu', 'lesson' => 5],
            ['character' => 'ゼ', 'sound' => 'ze', 'lesson' => 5],
            ['character' => 'ゾ', 'sound' => 'zo', 'lesson' => 5],
            ['character' => 'ダ', 'sound' => 'da', 'lesson' => 6],
            ['character' => 'ヂ', 'sound' => 'ji', 'lesson' => 6],
            ['character' => 'ヅ', 'sound' => 'zu', 'lesson' => 6],
            ['character' => 'デ', 'sound' => 'de', 'lesson' => 6],
            ['character' => 'ド', 'sound' => 'do', 'lesson' => 6],
            ['character' => 'バ', 'sound' => 'ba', 'lesson' => 6],
            ['character' => 'ビ', 'sound' => 'bi', 'lesson' => 6],
            ['character' => 'ブ', 'sound' => 'bu', 'lesson' => 6],
            ['character' => 'ベ', 'sound' => 'be', 'lesson' => 6],
            ['character' => 'ボ', 'sound' => 'bo', 'lesson' => 6],
            ['character' => 'パ', 'sound' => 'pa', 'lesson' => 7],
            ['character' => 'ピ', 'sound' => 'pi', 'lesson' => 7],
            ['character' => 'プ', 'sound' => 'pu', 'lesson' => 7],
            ['character' => 'ペ', 'sound' => 'pe', 'lesson' => 7],
            ['character' => 'ポ', 'sound' => 'po', 'lesson' => 7],
            ['character' => 'キャ', 'sound' => 'kya', 'lesson' => 7],
            ['character' => 'キュ', 'sound' => 'kyu', 'lesson' => 7],
            ['character' => 'キョ', 'sound' => 'kyo', 'lesson' => 7],
            ['character' => 'シャ', 'sound' => 'sha', 'lesson' => 7],
            ['character' => 'シュ', 'sound' => 'shu', 'lesson' => 7],
            ['character' => 'ショ', 'sound' => 'sho', 'lesson' => 7],
            ['character' => 'チャ', 'sound' => 'cha', 'lesson' => 7],
            ['character' => 'チュ', 'sound' => 'chu', 'lesson' => 7],
            ['character' => 'チョ', 'sound' => 'cho', 'lesson' => 7],
            ['character' => 'ニャ', 'sound' => 'nya', 'lesson' => 8],
            ['character' => 'ニュ', 'sound' => 'nyu', 'lesson' => 8],
            ['character' => 'ニョ', 'sound' => 'nyo', 'lesson' => 8],
            ['character' => 'ヒャ', 'sound' => 'hya', 'lesson' => 8],
            ['character' => 'ヒュ', 'sound' => 'hyu', 'lesson' => 8],
            ['character' => 'ヒョ', 'sound' => 'hyo', 'lesson' => 8],
            ['character' => 'ミャ', 'sound' => 'mya', 'lesson' => 8],
            ['character' => 'ミュ', 'sound' => 'myu', 'lesson' => 8],
            ['character' => 'ミョ', 'sound' => 'myo', 'lesson' => 8],
            ['character' => 'リャ', 'sound' => 'rya', 'lesson' => 8],
            ['character' => 'リュ', 'sound' => 'ryu', 'lesson' => 8],
            ['character' => 'リョ', 'sound' => 'ryo', 'lesson' => 8],
            ['character' => 'ギャ', 'sound' => 'gya', 'lesson' => 9],
            ['character' => 'ギュ', 'sound' => 'gyu', 'lesson' => 9],
            ['character' => 'ギョ', 'sound' => 'gyo', 'lesson' => 9],
            ['character' => 'ジャ', 'sound' => 'ja', 'lesson' => 9],
            ['character' => 'ジュ', 'sound' => 'ju', 'lesson' => 9],
            ['character' => 'ジョ', 'sound' => 'jo', 'lesson' => 9],
            ['character' => 'ビャ', 'sound' => 'bya', 'lesson' => 9],
            ['character' => 'ビュ', 'sound' => 'byu', 'lesson' => 9],
            ['character' => 'ビョ', 'sound' => 'byo', 'lesson' => 9],
            ['character' => 'ピャ', 'sound' => 'pya', 'lesson' => 9],
            ['character' => 'ピュ', 'sound' => 'pyu', 'lesson' => 9],
            ['character' => 'ピョ', 'sound' => 'pyo', 'lesson' => 9],
            ['character' => 'ッカ', 'sound' => 'kka', 'lesson' => 10],
            ['character' => 'ッス', 'sound' => 'ssu', 'lesson' => 10],
            ['character' => 'ット', 'sound' => 'tto', 'lesson' => 10],
            ['character' => 'ップ', 'sound' => 'ppu', 'lesson' => 10],
            ['character' => 'ッリ', 'sound' => 'rri', 'lesson' => 10],
            ['character' => 'アー', 'sound' => 'aa', 'lesson' => 10],
            ['character' => 'イー', 'sound' => 'ii', 'lesson' => 10],
            ['character' => 'ウー', 'sound' => 'uu', 'lesson' => 10],
            ['character' => 'エー', 'sound' => 'ee', 'lesson' => 10],
            ['character' => 'オー', 'sound' => 'oo', 'lesson' => 10],
        ];

        foreach ($characters as $character) {
            Katakana::create($character);
        }
    }
}
